'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

    
    const postData = [
      {
          privacy: false,
              email: 'antoniomorares@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Educación gratuita y de calidad. Es una demanda que se ha escuchado bastante en los últimos años y que, sin duda, es nec',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jeff1315@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'De forma corta, uno de los mayores problemas son los bajos sueldos en relación a los altos gastos de una familia en Chil',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'METRO: Que cobren 500 pesos a gente con ingresos menores de 500.000 mensual y el resto paga la tarifa normal. Que exista',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Domingasilvav@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Educación en empresas: Que las empresas que tengan más de una cantidad de trabajadores tengan colegios gratuitos para lo',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Ideas para incentivar la profesión de pedagogía en colegios públicos: subir sueldos a profesores, y mejor ambiente, ya s',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'cihlhe@hotmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Lograr mejorar las pensiones, existiendo un fondo de reparto en el que se vaya contribuyendo de acuerdo a la propia situ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'cuando Miembros de la tercera edad decidan trabajar. Sus trabajos deben ser libres de impuestos, enfocado al sector más ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las empresas entreguen su asignación de transporte cargando directamente la tarjeta Bip! del trabajador. Así se evit',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Aunento al impuesto a las empresas, sumado a un aumentos gradual de esto para empresas nuevas. O sea, cuando se cree una',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Creación de la posibilidad de pagar una mensualidad en la tarjeta Bip, con un cobro de 20000 pesos por dos viajes diario',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Las empresas sanitarias que abastecen de agua potable deben realizar un catastro de las zonas de pérdida de la red (medi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los jubilados como mínimo tengan como pensión igual o mayor al sueldo mínimo ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'gustavoaaz@gmail.com ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Dieta parlamentaria: Que el sueldo de los parlamentarios sea igual al sueldo promedio de un trabajador con la misma prof',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear un sistema de pensiones que crezca de manera gradual basado no en los ingresos, sino que en el consumo. Mediante e',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Legalizacion de todas las drogas',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Debería haber un ramo obligatorio en el curriculum escolar de educación cívica. Es absolutamente necesqrio que la gente ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'i_retamal.ct',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Construcción de viviendas sociales en varios barrios/comunas con bajo índice de vulnerabilidad. Con acceso a servicios p',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Invertir mucho más en ciencia y tecnología pues así se generarán mejores escenarios para invertir en otras áreas en el f',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el cae siga funcionando tal como ahora, pero sin intereses',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Cambiar el sistema presidencialista actual en Chile,  por uno semi-presidencialista. Para darle mayores atribuciones al ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ariel.kauderer@uc.cl',
              instagram: 'ari_kauderer',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Sistema de vouchers para educación. No puede ser que el Estado gaste cerca de 500.000 por alumno al mes y no sea capaz d',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'valdes.benjamin1@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Lo que más le ha dolido a la gente y la ha hecho manifestarse es una rabia que a mi gusto tiene como origen principal lo',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'federeatamal500@gmail.com ',
              instagram: 'federico _retamal ',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Un cambio en el sistema de partidos, ya que en el actual solo llegan arriba los mas inútil, los que estan de acurdo con ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Felipefrancodiaz',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el estado le asegurase a toda persona una jubilación mínima equivalente al sueldo mínimo rigente, en caso que el mon',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Felipefrancodiaz',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el estado de Chile asegure por ley de que las empresas nacionales e internacionales que extraen recursos mineros com',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'maximiliano.fabres',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Desprivatizar las carreteras y los aparcamentos estatales, ya que las calles del país son de la población',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propuesta legal de irlanda. Cada cargo equivalente de una empresa, para empleados posteriores a los 6 mese de contratado',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El sistema de previsión obligarlo de salud (fonasa, isapre), debiese trabajar de la misma forma que en países desarrolla',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'No tengo instagram',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Independización de algunos servicios del estado: JUNJI, SENAME, SENAMA, SML, JUNAEB, SERNAGEOMIN, y servicios público/pr',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Impuestos según región. No más centralismo SII. Independencia tributaria a las regiones. Qué cada región tenga el poder ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear una cuenta de afp con 1 millón ( o más) para cada recién nacido, para que al jubilar, debido al interés compuesto,',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que la gente del congreso viva, haya vivido, o por último conozca los lugares a los cuales representa.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear, al igual que en muchos países, el pago mensual del transporte publico. Que exista la posibilidad de pagar por el ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Tener ingreso mínimo diferido con apoyo estatal. En otras palabras, tener un sueldo mínimo estandar, y para las mipymes ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Agregar a la constitución una declaración de derechos del contribuyente, parecida a la de Colorado (TABOR), para que el ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: ' Vivienda pública con una fuertísima preocupación por el diseño. Bien ubicada y con uso de suelo mixto. Como referencia ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'plcarmona@uc.cl',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Replantear la educación de raíz.  El sistema de educación actual está obsoleto, sin tener que reinventar la educación se',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'plcarmona@uc.cl',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Implementar la modalidad &quote&Co-housing&quote&   Consiste en viviendas donde hay áreas en común el cual todos tienen ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que la gratuidad de educación superior se plantee como un préstamo del Estado, de forma que se estudie gratis pero que u',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el impuesto al tabaco y el alcohol. Que productos como estos tengan mayor impuesto, de forma de aumentar el tes',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Destinar cierta cantidad de los impuestos por IVA a “rellenar” imposiciones de personas con lagunas en las AFP de forma ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Desincentivar el uso del automóvil particular aplicando impuestos o restricciones. La única forma de romper con el círcu',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ygorodischer@uc.cl',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Los costos de movilización deberían ser a cargo del empleador, en la medida que sea posible. Las empresas podrían tener ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ygorodischer@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el impuesto a la contaminación de las termoeléctricas. De esta manera se recaudan más fondos y se incentiva a q',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Mi propuesta busca iniciar una mejora en torno a la dignidad que le correspone a cada persona.   La educación, la previs',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fin de las AFP',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el numero de hospitales y  médicos que atiendan por el sistema público, además de que se faciliten todos los me',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Si las Isapres se realizan acciones que no son legales contra los usuarios (específicamente en las alzas de planes) que ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Al momento de jubilar, permitir que se  retire un porcentaje de los ahorros por lo menos 50%.   Si la persona fallece, q',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Nacionalización de recursos naturales. Que el agua deje de ser privada y de unos pocos.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que todas ls personas que están privadas de libertad (prisión) trabajen y aporten a la comunidad, para que no tengamos q',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las grandes empresas utilicen parte de sus utilidades en generar más puestos de trabajo, mediante proyectos comunita',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Sanciones reales para empresarios que se coluden. Las clases de ética y multas no son suficientes.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que las AFP vuelvan a lo que se había definido inicialmente. Que las pérdidas de los fondos no afecten a los usuarios.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que quienes tengan cargos por corrupción no puedan tener cargos públicos.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Quitar la preexistencia de las isapres. Mucha gente no puede optar a mejor nivel de salud por una preexistencia, colpasa',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bajar gradualmente el IVA, que es un impuesto que afecta a los más pobres. Compensar el déficit fiscal bajando gastos de',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Cecilia.moraga77@gmail.com ',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Que el sistema de salud de los uniformados (de cualquier índole, desde carabineros hasta militares como tal), sea el mis',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Rodrigofdez',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Elaboración de canasta básica de alimentos a los cuales se les aplique un IVA rebajado o estén exentos. Se ataca directa',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Dieta parlamentaria: sueldos en sector publico sean máximo 15 veces el sueldo mínimo (incluyendo al presidente), y que l',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Se me olvido de lo que puse recién.    Reforma laboral para mejorar la forma de cotizar de las personas. Que las persona',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '1. El legislador (diputado o senador) será asalariado solamente durante su mandato. Y no tendrá jubilación proveniente e',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: ' Todo legislador (pasado, presente y futuro) que actualmente contribuye al fondo de jubilación del Parlamento pasará al ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Milivoj1',
              type: 'Proyecto dirigido a empresas',
              body: 'Recuperar empresas que fueron estatales, como Soquimich, adquiridas por privados ( yerno de Pinochet - Ponce Lerou) dura',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jtleyton10@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '-Eliminar IVA para productos de canasta básica  -Ley que haga compartir perdidas entre civiles y afps  -Reducir impuesto',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que sea parte del curriculum nacional ramos específicos y obligatorios de ética y educación cívica desde primer ciclo pa',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'selsaca@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Piñera hablo sobre subsidiar sueldos para que lleguen a 350 mil pesos. Sería ideal que en vez de 350 mil pesos sean 375 ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que ningun arancel mensual de universidad/colegio sobrepase el sueldo mínimo. ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ranelson@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propongo volver a estudiar la asignación de viáticos para parlamentarios. ¿Realmente es necesario que un parlamentario d',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que el tiempo de viaje de los trabajadores sea contado como horas de trabajo. Esto busca cuidar que efectivamente las pe',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: '@p.lira.z',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reducir el IVA ayudaría a reducir el costo de la vida, pero ello tendría que ir de la mano con un aumento de los impuest',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Desde ya y hacia el futuro hombres y mujeres trabajarán indistitamente. Sin embargo, el cuidado de los niños por sus pad',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los parlamentarios tengan un sueldo normal, no exorbitante, para que la gente esté ahí por vocación y no por interés',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar los sueldos vitalicios para nuestros presidentes.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Optimizar el trabajo de la cámara de diputados sesionando remotamente y delegando el trabajo distrital de campo y de com',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Flvivanco@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear un filtro que verifique la vocación real de la persona cuando postule a un cargo público. Es decir, asegurarse (o ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Actualizar nuestro código penal, penas más duras a las situaciones que verdaderamente nos aquejan, para los delitos de c',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'gargantua5799@gmail.com',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Creo que debería haber un sueldo base de 500 mil pesos a todas las personas que cumplen el rol de cuidador de un sujeto ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Trabajar en que los recursos sean más que suficientes para el SENAME y que NO se aguante una VIOLACIÓN más a los derecho',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Así mismo, no abandonen a nuestra población de adultos mayores, la cual va cada vez más en incremento.   Piensen que mer',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Actualizar nuestro código penal, penas más duras a las situaciones que verdaderamente nos aquejan, para los delitos de c',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Estatizar la producción y distribución eléctrica, financiar la inversión estructural con dineros previsionales.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Estatizar la producción y distribución eléctrica, financiar la inversión estructural con dineros previsionales.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Todos los nuevos proyectos de infraestructura (puentes, caminos, carreteras, puertos, aeropuertos, túneles, etc) financi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Ngiturrate ',
              type: 'Proyecto dirigido a empresas',
              body: 'Sistema de pago en supermercados por bandas. Todo aquel que tenga un ingreso menor a $400.000 pague la mitad del total d',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ripacn2@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Básicamente que los funcionarios públicos, en especial de alto mando (presidente, ministros, etc), solo puedan ocupar lo',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Enfermedades de salud mental cubiertas por el plan Auge ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Analizar bien los huella de carbono e hídrica de diversos productos y generar un impuesto verde para poder recaudar más ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Mejor calidad de profesores',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Alonc.w',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Disminuir la segregación a base de un impusto sectorizado. La idea es que favoresca a las empresas que opten por ponerse',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El salario de los cargos públicos dependerá de la asistencia y cumplimiento de sus labores (ej. Diputado que no va a una',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '1) Bajar dieta parlamentaria en un 50% (sigue siendo un sueldo de lujo igual)  2) Que eliminen el sueldo vitalicio a los',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Aliagamv@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Respetar y fortalecer la familia,devolviendole la autoridad y responsabilidad a los padres',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Elaborar planes de reinserción social para disminuir el ciclo delictivo al salir de la carcel, enfocandose en el problem',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Jaime-bravo@live.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Resignación de presupuestos y mayor aporte de municipalidades más ricas a más pobres ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que a cada auto al momento de la revisión técnica se le asigné un número, proporcional a cuánto contamina y en base a es',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Poner en urgencia la corrección del artículo 8 de la ley 20780, donde establece que el costo por pago del impuesto a las',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'IVA diferenciado según tipo de bienes:   Canasta familiar básica (iva 10 %)  Bienes de lujo, cigarrillos, alcohol y auto',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Valentinakobus@gmail.com',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Someter a consulta ciudadana formal (plebiscito) la aprobación del TPP-11. Es una decisión que nos afectará a todos; tan',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reducir cantidad de apitutados políticos en municipalidades, gobernaciones, etc.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar el hecho de que los empleados públicos no puedan ser echados ni evaluados por desempeño',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'lfgarridom@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Castigos ejemplares para actos de colusión y de corrupción. Que sea mayor la penalización que lo incurrido en daños (por',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Aumentar los cupos en la carrera medicina y otras carreras de la Salud. Hay tantos estudiantes hiper inteligentes y tale',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Jt.loayza',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Asamblea constituyente y cambios estructurales ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Establecer un monto máximo que pueden recibir los cargos de las empresas asociadas al estado y licitaciones estatales co',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Otorgar al Sernac de capacidad fiscalizadora  real,  que le  duela a quien trate de coludirse , falsear precios  o engañ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Educación es el punto de inflexión de un país. No debiera ser manipulada por el gobierno u otro poder económico de turno',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Mrgonzalez@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear más espacios abiertos de divulgación científica. Propongo que la ciencia y la tecnología se tomen el espacio públi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Comisión del ministerio de hacienda que busque identificar y sancionar CONSIDERABLEMENTE a los evasores de impuestos y r',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'desprivatizar el agua',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propuesta para mejorar la eduación básica y media en Chile que persiste aúm hasta el actual año 2019:    Crear un proyec',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Fenatellez',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '1) Educar a las personas respecto al funcionamiento de las AFP (Top 10 sistema de pensión a NIVEL MUNDIAL)  2) Hacer que',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bajar el IVA, que actualmente es de un 19% a un 4% para los productos de primera necesidad tales como: agua, artículos d',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Prohibir y regular ciertos proyectos inmobiliarios tales como guetos verticales y “nanodepartamentos”, establecer cantid',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Creación de una app oficial, segura y gratuita a la que se cree una cuenta asociada a el rut y una contraseña, mediante ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminación de los conservadores de bienes raíces. En el sistema actual, son designados por el presidente de la repúblic',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Hacer una ley de donación con importantes beneficios tributarios para que las empresas puedan donar para la reconstrucci',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'j.catalanvillablanca@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Mejoras crédito CAE',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar de manera considerable el impuesto a las drogas legales, como el alcohol, el tabaco y los cigarros.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Seguro universal de salud, transformando a isapres a empresas de seguro complementario donde un porcentaje tenga que ir ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Cambio de modelo. Estado subsidiario. Redistribuir ganancias de bienes nacionales e impuestos, en un orden de prioridade',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'La anulación del TPP-11 ya que se aprovo durante el movimiento social y su alto costo a la calidad de vida de los chilen',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Josefa.vasquez@usach.cl',
              instagram: 'Josefaypunto',
              type: 'Proyecto ciudadano',
              body: 'Mejorar la salud mental calando en los determinantes sociales ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Por que ir en contra de la naturaleza? La desigualdad existe y seguirá existiendo. Si uno quiere imponerse ante la adver',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'soficlement',
              type: 'Proyecto ciudadano',
              body: 'buses con bicileteros y mejorar la conectividad de las ciclovías en Santiago. ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'vmonttb@yahoo.es',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear leyes duras en cuanto a la seguridad. Si te asaltan que cumplan penas en la carcel, si es necesario construir mas ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'fran_4399@hotmail.com ',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Desde hace años que todos hemos escuchado el término educación de calidad, sin embargo, nunca hemos especificado a qué n',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'fran_4399@hotmail.com ',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Sin duda, los vínculos sociales son esenciales para la vida de cada ciudadano, por lo que la calidad de vida cambiaría s',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fondos para hacer de chile un país turistico',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que se nos calcule y pagué a todos pensiones como si viviéramos hasta los 83 y 88 años (hombres y mujeres), los que vive',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear una tarifa mensual en el sistema de transporte publico que este unida al rut de cada persona, no como la actual ta',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Lucas.cortes@mail.udp.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Somos de los países con mayores impuestos de la ocde. Ya sabemos que el estado no administra bien los recursos, y Piñera',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Libros sin IVA',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fijar los sueldos en unidades de fomento (UF), y así evitar la pérdida de poder adquisitivo de los trabajadores, ya que,',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Asamblea constituyente, es clave!!',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los politicos tengan que demostrar que estan capacitados para ejercer su cargo (titulo de autoridad en su area), asi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'L@s estudiantes de Medicina, una vez terminada la carrera, deberían realizar una práctica obligatoria por una cierta can',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Sueldo mensual que puede ser equivalente a lo que ganan los militares o carabineros para cada deportista seleccionado na',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Recorte de gastos innecesarios como asistentes políticos y trabajadores gubernamentales innecesarios, y igualar la propo',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar la reforma a afps realizada por Lagos. Esto significa que afiliados dejen de asumir las perdidas de las afps. N',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las empresas les paguen, al mes de Octubre los bonos por ventas a los trabajadores',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Hagamos que los sueldos de cargos públicos no sean fijos, sino que se limiten a mantener la vida de los funcionarios. En',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Jocelyn.kdh@gmail.com ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Cambiar a los administradores de los centros de salud, en todos sus niveles, los médicos deben salvar vidas, atender a l',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jocelyn.kdh@gmail.com ',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Evaluar la calidad del apoyo tecnológico que tienen los centros de salud, desde su infraestructura tecnológica, hasta la',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'flodonoso4',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fijación de precios para consultas médicas, operaciones, intervenciones médicas y dentales.  Hoy en día se lucra mucho c',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jocelyn.kdh@gmail.com ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Con la eficiencia que tiene Metro en el uso de los recursos, la experiencia en en transporte público y la cantidad de di',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'mrafols@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '[Ahorro Solidario Intrageneracional] Que el sistema solidario de pensiones sea por un ahorro entre los miembros de una g',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El PIE (proyecto de inclusión escolar) debería ser implementado en todos los colegios sin excepción asegurándose de adap',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bajar el impuesto a la comida ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Establecer una carta de deberes civiles para la ciudadanía para que ellos tengan la responsabilidad de velar y mantener ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar las restricciones anuales de atenciones de profesionales de  rehabilitación en el sistema FONASA para las perso',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los doctores tengan la obligación de trabajar en el servicio público (hospitales, APS)  al menos un 20% de su jornad',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reforzar los centros de Atención Primaria en Salud con mayor cantidad y variedad de profesionales de la salud. Fomentand',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Que la clase politica DEBA ser ejemplo en el cumplimiento de la ley. Así, que si un político incumple con la ley tenga m',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'drvalle@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que las dietas parlamentarias sean proporcionales al Sueldo Mínimo y que a los diputados y senadores se les pague de acu',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'drvalle@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las empresas cambien sus casas matrices a las regiones donde tienen su operación. Que paguen sus impuestos y patente',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Ya hemos hecho un gran trabajo etiquetando todos los alimentos altos en calorías, grasas y azúcares que sin duda perjudi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El impuesto específico existente a la bencina se aplicó para restaurar carreteras destruidas el año 1985, y aún sigue vi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Drvalle@gmail.com',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Transformar nuestro Sistema de Salud Curativo a uno Preventivo. Debiésemos enfocarnos en evitar las enfermedades desde u',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ptmedina@uc.cl',
              instagram: 'Pablomedina980',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que al momento de comprar cualquier cosa en la boleta aparezca el monto exacto de la parte del precio que corresponde al',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar el impuesto específico ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Gaboxix@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bueno hola parto con saludar, ya que encuentro bacan que estén dando estas instancias a la gente para poder expresar su ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el sueldo de los profesores. ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Stephitrautmann',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Para mejorar la educación, la carrera de pedagogía debería estar al mismo nivel que la carrera de medicina en términos d',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aborto libre y seguro ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Mayor acceso a la cultura para todos los niveles socioeconómicos',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Se necesita invertir en el servicio de inteligencia.',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'En E.E.U.U. existe el “earned income tax credit” donde a las personas más vulnerables se les devuelve parte del pago de ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'elisarriagada97@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Se debiera hacer una “canasta básica de alimentos” que contenga todos los alimentos básicos y necesarios para una dieta ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'No se debería cobrar IVA a los productos de primera necesidad. Esto incluye medicamentos, pañales, confort, productos de',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'elisarriagada97@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Continuando con mi propuesta anterior, se debería hacer una “canasta básica de medicamentos y productos farmacéuticos bá',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Mabelperez31@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'En salud cambiar al ministro, sanciones más drásticas a la colisión, aumentar el recurso destinado a este item... Mejora',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Karinmas',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que la educacion no sea un negocio, debe ser entregada por el Estado y que funcione, deberian cobrar impuestos (proporci',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'En relacion a la propuesta que dice fijar precios maximos a horas de medicos, eso dificilmente es realizable. Sin embarg',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'La gran mayoría de los problemas de la salid pública en Chile, se deben al mal manejo de los recursos entregados. Por lo',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Exigir en cada carrera que sus alumnos participen en algún proyecto social. Desde una fundación, hasta incluso una práct',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Ya que es dificil implementar cambios bruscos al sistema de AFPs, se podría implementar YA! que todos los pensionados re',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Proyecto a clases sociales que no tienen acceso a cultura y educación de calidad a través de workshops para enseñarles d',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'arichuaqui',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Volver al voto obligatorio y mantener la inscripción automática. Estos últimos días se ha hablado mucho sobre lo corromp',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reducir el número de congresistas a 120 diputados y 40 senadores, manteniendo sistema proporcional y distritaje (más de ',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Qué pasa con :  - Grandes Grupos económicos chilenos que han obtenido sus increíbles ganancias y no las invierten en Chi',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'mjdiestre@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: ' Para bajar los precios del metro para los primeros quintiles (personas con menor ingreso), podrían eliminar la universa',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propongo enseñar educación socioemocional a las chilenas y chilenos desde la primera niñez y a lo largo de toda la educa',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Becas 100% Universidad Del Pacifico',
              status: 'pendiente',
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      ];
      
    /*

      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkInsert('People', [{
        name: 'John Doe',
        isBetaMember: false
      }], {});
    */
   return queryInterface.bulkInsert('posts', postData);

  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
   return queryInterface.bulkDelete('posts', null, {});

  }
};
