'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

    const postData = [
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los parlamentarios reduzcan su numero a máximo 40, senadores dos por regiones muy pobladas y 1 por el resto de las regiones ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'David.ag.y@hotmail.cl',
              instagram: 'David.ag.y',
              type: 'Proyecto ciudadano',
              body: 'Realizar consultas ciudadanas estilo plebiscito , al momento de tomar decisiones en temas sociales y que pueden afectar a la comunidad , temas como el aborto , sueldos de parlamentarios (aumento o disminución ), matrimonio igualitario  o temas de similare',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el impuesto suba a un 60% para todos pero la educación, la salud, el tranporte  y la educación superior sean gratuitos y de muy buena calidad ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Mejorar lo que hace que la gente viva de manera digna que le alcance para llegar a fin de mes y sin endeudarse de por vida ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'antoniomorares@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Educación gratuita y de calidad. Es una demanda que se ha escuchado bastante en los últimos años y que, sin duda, es necesaria de satisfacer. Por otro lado, el mundo está experimentando una época de digitalización de la información, cada vez es más fácil ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jeff1315@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'De forma corta, uno de los mayores problemas son los bajos sueldos en relación a los altos gastos de una familia en Chile. Una propuesta podría ser un incentivo a las empresas de bajarle tasas de imposición, si suben los sueldos de sus empleados no gerenc',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'METRO: Que cobren 500 pesos a gente con ingresos menores de 500.000 mensual y el resto paga la tarifa normal. Que exista un tope mensual (40.000 por ejemplo) en el q puedas tener infinitos viajes sino, de lo contrario los otros montos',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Domingasilvav@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Educación en empresas: Que las empresas que tengan más de una cantidad de trabajadores tengan colegios gratuitos para los hijos de estos. Las empresas así se hacen responsables y entregan una educación de calidad.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Ideas para incentivar la profesión de pedagogía en colegios públicos: subir sueldos a profesores, y mejor ambiente, ya sea: menos estudiantes por clases, dar menos clases a cada profesor, así ellos van a poder organizar mejor sus clases, hacer mejores gui',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'cihlhe@hotmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Lograr mejorar las pensiones, existiendo un fondo de reparto en el que se vaya contribuyendo de acuerdo a la propia situación económica. Además de planificar de mejor forma la distribución de recursos en los hospitales',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'cuando Miembros de la tercera edad decidan trabajar. Sus trabajos deben ser libres de impuestos, enfocado al sector más vulnerable. Así no pagan doble tributación por pensión y trabajo.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las empresas entreguen su asignación de transporte cargando directamente la tarjeta Bip! del trabajador. Así se evita la evasión, se fomenta el transporte público y la asignación de transporte se utiliza para lo que realmente se asigna.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Aunento al impuesto a las empresas, sumado a un aumentos gradual de esto para empresas nuevas. O sea, cuando se cree una nueva empresa, o una empresa extranjera ingrese a chile, rebajarle los impuestos el primer año, subirlos a un punto medio el segundo (',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Creación de la posibilidad de pagar una mensualidad en la tarjeta Bip, con un cobro de 20000 pesos por dos viajes diarios. Además la posibilidad de cobrar 15000 para el quintil de menores ingresos. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Las empresas sanitarias que abastecen de agua potable deben realizar un catastro de las zonas de pérdida de la red (mediante sondaje u otras técnicas) y crear un plan de reparación para las tuberías en mal estado o rotas. Actualmente un 30% del agua potab',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los jubilados como mínimo tengan como pensión igual o mayor al sueldo mínimo ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'gustavoaaz@gmail.com ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Dieta parlamentaria: Que el sueldo de los parlamentarios sea igual al sueldo promedio de un trabajador con la misma profesión, considerando grado de estudio, universidad o instituto donde estudió (cuando corresponda), años de titulado, etc. Esto permitirí',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear un sistema de pensiones que crezca de manera gradual basado no en los ingresos, sino que en el consumo. Mediante el Iva destinar parte de ese consumo de cada ciudadano a un fondo de ahorro. De esta manera, se incentiva el uso de boletas, ademas de r',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Legalizacion de todas las drogas',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Debería haber un ramo obligatorio en el curriculum escolar de educación cívica. Es absolutamente necesqrio que la gente aprenda cómo se forma el gobierno, pagar impuestos, y cómo funciona nuestro país. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'i_retamal.ct',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Construcción de viviendas sociales en varios barrios/comunas con bajo índice de vulnerabilidad. Con acceso a servicios públicos básicos.  Esta viviendas no estarán a la venta, se darán subsidios de arriendo a los beneficiaros. Existe evidencia académica d',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Invertir mucho más en ciencia y tecnología pues así se generarán mejores escenarios para invertir en otras áreas en el futuro.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el cae siga funcionando tal como ahora, pero sin intereses',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Cambiar el sistema presidencialista actual en Chile,  por uno semi-presidencialista. Para darle mayores atribuciones al Congreso y hacer de los representes un cargo más propositivo de políticas públicas de lo que es ahora.\nHe oído muchos comentarios crit',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ariel.kauderer@uc.cl',
              instagram: 'ari_kauderer',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Sistema de vouchers para educación. No puede ser que el Estado gaste cerca de 500.000 por alumno al mes y no sea capaz de brindar educación decente',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'valdes.benjamin1@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Lo que más le ha dolido a la gente y la ha hecho manifestarse es una rabia que a mi gusto tiene como origen principal los robos de instituciones y la desconfianza hacia estas, más que la misma dificultad económica que las familias atraviesan. Es por esto ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'federeatamal500@gmail.com ',
              instagram: 'federico _retamal ',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Un cambio en el sistema de partidos, ya que en el actual solo llegan arriba los mas inútil, los que estan de acurdo con todos y con nadie, dejando la puerta abierta para gente inepta que lo unico que intenta es no perder el apoyo. Propongo uno que ponga p',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Felipefrancodiaz',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el estado le asegurase a toda persona una jubilación mínima equivalente al sueldo mínimo rigente, en caso que el monto de la jubilación sea inferior a este.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Felipefrancodiaz',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que el estado de Chile asegure por ley de que las empresas nacionales e internacionales que extraen recursos mineros como por ejemplo el cobre y el litio, paguen un "royalty". De esta forma, el estado de Chile poseerá más dinero para temas nacionales como',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'maximiliano.fabres',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Desprivatizar las carreteras y los aparcamentos estatales, ya que las calles del país son de la población',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propuesta legal de irlanda. Cada cargo equivalente de una empresa, para empleados posteriores a los 6 mese de contratado debe recibir el mismo sueldo bruto (Con desviaciones no mayores al 3%). A menos que la empresa tenga medidas de desempeño para dicho c',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El sistema de previsión obligarlo de salud (fonasa, isapre), debiese trabajar de la misma forma que en países desarrollados. No discriminar por genero, y no poseer preexistencias.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'No tengo instagram',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Independización de algunos servicios del estado: JUNJI, SENAME, SENAMA, SML, JUNAEB, SERNAGEOMIN, y servicios público/privados como la CONAF de tal forma que la cabeza no sea una persona asignada por el gobierno de turno. Dicho en fácil, que la persona a ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Impuestos según región. No más centralismo SII. Independencia tributaria a las regiones. Qué cada región tenga el poder sobre el régimen impositivo que se aplique en su región. Parlamentarios por región tendrían la facultad de proponer y votar por estos t',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear una cuenta de afp con 1 millón ( o más) para cada recién nacido, para que al jubilar, debido al interés compuesto, tenga asegurado decenas de millones en su cuenta.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que la gente del congreso viva, haya vivido, o por último conozca los lugares a los cuales representa.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear, al igual que en muchos países, el pago mensual del transporte publico. Que exista la posibilidad de pagar por el uso del transporte publico de forma mensual, que generalmente es una cifra bastante reducida, y así cobrar en una mayor cantidad por tr',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'mlucasl',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Tener ingreso mínimo diferido con apoyo estatal. En otras palabras, tener un sueldo mínimo estandar, y para las mipymes tener un sueldo mínimo diferido con apoyo estatal. Parecido al proyecto propuesto por el presidente, pero con el apoyo estatal solo a l',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Agregar a la constitución una declaración de derechos del contribuyente, parecida a la de Colorado (TABOR), para que el gobierno sea más eficiente con el presupuesto',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: ' Vivienda pública con una fuertísima preocupación por el diseño. Bien ubicada y con uso de suelo mixto. Como referencia el plan de vivienda pública de EEUU de 1937. No caro, bien hecho.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'plcarmona@uc.cl',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Replantear la educación de raíz.\nEl sistema de educación actual está obsoleto, sin tener que reinventar la educación se puede simplemente copiar los sistemas de educación de Finlandia o Noruega. \nSi queremos ir más lejos debemos crear un sistema educati',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'plcarmona@uc.cl',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Implementar la modalidad "Co-housing" \nConsiste en viviendas donde hay áreas en común el cual todos tienen acceso, como el comedor, la cocina, etc. Y el sector privado con los dormitorios baños y living.\nLos beneficios son varios:\n-Viviendas más barata',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que la gratuidad de educación superior se plantee como un préstamo del Estado, de forma que se estudie gratis pero que una vez terminada la carrera la persona tenga que devolverle al Estado cierto porcentaje de su sueldo (5%-10% dependiendo)  por cierta c',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el impuesto al tabaco y el alcohol. Que productos como estos tengan mayor impuesto, de forma de aumentar el tesoro estatal. Esto sería un win win, ya que al no fomentar su consumo se vela también por la salud de las personas, lo cual en el largo ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Destinar cierta cantidad de los impuestos por IVA a “rellenar” imposiciones de personas con lagunas en las AFP de forma que su pensión sea un poco mayor. Además, si al pagar el IVA hay platas destinadas a pensiones se incentiva a la gente a exigir su bole',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Desincentivar el uso del automóvil particular aplicando impuestos o restricciones. La única forma de romper con el círculo vicioso del transporte público es que la gente se baje del auto para que haya menor congestión (y contaminación) para que así los ti',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ygorodischer@uc.cl',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Los costos de movilización deberían ser a cargo del empleador, en la medida que sea posible. Las empresas podrían tener un sistema al estilo cheque de restaurant, en el que le entreguen a cada uno de sus empleados una bip con carga para un mes (2 veces po',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ygorodischer@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el impuesto a la contaminación de las termoeléctricas. De esta manera se recaudan más fondos y se incentiva a que se desarrollen energías limpias. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Mi propuesta busca iniciar una mejora en torno a la dignidad que le correspone a cada persona. \nLa educación, la previsión de salud y las pensiones, son bienes que no deben pertenecer al mercado, sino que deben ser entregados por el Estado de manera equi',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fin de las AFP',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el numero de hospitales y  médicos que atiendan por el sistema público, además de que se faciliten todos los medicamentos necesarios a las personas, de está manera la gente no desenbolsaría más dinero en salud, que el 7% de todos los meses.\n',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Si las Isapres se realizan acciones que no son legales contra los usuarios (específicamente en las alzas de planes) que el gobierno proceda a multarlos, sin tener necesidad cada usuario de demandarlas de forma individual.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Al momento de jubilar, permitir que se  retire un porcentaje de los ahorros por lo menos 50%. \nSi la persona fallece, que los ahorros pasen a sus herederos en su totalidad y sin condiciones especiales.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Nacionalización de recursos naturales. Que el agua deje de ser privada y de unos pocos.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que todas ls personas que están privadas de libertad (prisión) trabajen y aporten a la comunidad, para que no tengamos que mantenerlos totalmente con dineros fiscales.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las grandes empresas utilicen parte de sus utilidades en generar más puestos de trabajo, mediante proyectos comunitarios, de innovación, investigación, etc.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Sanciones reales para empresarios que se coluden. Las clases de ética y multas no son suficientes.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que las AFP vuelvan a lo que se había definido inicialmente. Que las pérdidas de los fondos no afecten a los usuarios.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que quienes tengan cargos por corrupción no puedan tener cargos públicos.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Quitar la preexistencia de las isapres. Mucha gente no puede optar a mejor nivel de salud por una preexistencia, colpasando el sistema público (cuando muchas veces podrían optar al sistema privado). Esto aumentaría la competencia entre isapres (beneficios',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bajar gradualmente el IVA, que es un impuesto que afecta a los más pobres. Compensar el déficit fiscal bajando gastos del estado.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Cecilia.moraga77@gmail.com ',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Que el sistema de salud de los uniformados (de cualquier índole, desde carabineros hasta militares como tal), sea el mismo que para el resto del país y que coticen en el mismo lugar que los demás, demás que no se juvilen a los 25 años de servicio, cuando ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Rodrigofdez',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Elaboración de canasta básica de alimentos a los cuales se les aplique un IVA rebajado o estén exentos. Se ataca directamente el problema del elevado costo de vida. \n\nEl argumento de la dificultad contable de tener IVA distintos es anulado con la experi',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Dieta parlamentaria: sueldos en sector publico sean máximo 15 veces el sueldo mínimo (incluyendo al presidente), y que las asignaciones de parlamentarios no superen el sueldo que gana este. Disminución de cantidad de parlamentarios. Mayor exigencia de asi',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Se me olvido de lo que puse recién.\n\nReforma laboral para mejorar la forma de cotizar de las personas. Que las personas con negocios independientes y que trabajan a honorarios también cotizen de una forma mas efectivas para que no hayan lagunas.\n\nMayo',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '1. El legislador (diputado o senador) será asalariado solamente durante su mandato. Y no tendrá jubilación proveniente exclusivamente por el mandato. (éste será un aporte mas)',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: ' Todo legislador (pasado, presente y futuro) que actualmente contribuye al fondo de jubilación del Parlamento pasará al régimen vigente de la Seguridad Social. El legislador participará de los beneficios dentro del régimen de la jubilación exactamente com',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Milivoj1',
              type: 'Proyecto dirigido a empresas',
              body: 'Recuperar empresas que fueron estatales, como Soquimich, adquiridas por privados ( yerno de Pinochet - Ponce Lerou) durante la dictadura y de manera poco lícita, y que manejan gran parte del mercado de no metálicos y minerales estratégicos como el Litio. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jtleyton10@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '-Eliminar IVA para productos de canasta básica\n-Ley que haga compartir perdidas entre civiles y afps\n-Reducir impuestos a PYMES\n-Privatizar agua (no a través de licencias, ni derecho de aprovechamiento)\n P R I V A T I Z A R para que vuelva a manos de ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que sea parte del curriculum nacional ramos específicos y obligatorios de ética y educación cívica desde primer ciclo para que se les inculque desde pequeños el buen actuar dentro de una sociedad.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'selsaca@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Piñera hablo sobre subsidiar sueldos para que lleguen a 350 mil pesos. Sería ideal que en vez de 350 mil pesos sean 375 mil pesos y que estos sean cubiertos por las empresas grandes. Mientras que el subsidio vaya cubierto para pequeñas y medianas empresas',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que ningun arancel mensual de universidad/colegio sobrepase el sueldo mínimo. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ranelson@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propongo volver a estudiar la asignación de viáticos para parlamentarios. ¿Realmente es necesario que un parlamentario de Valparaiso perciba la misma asignación de recursos que un representante de Arica? Propongo que la asignación de viaticos a parlamenta',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que el tiempo de viaje de los trabajadores sea contado como horas de trabajo. Esto busca cuidar que efectivamente las personas no usen su tiempo de recreacion, descanso y ocio en viajar al trabajo. Habria un incentivo a contratar gente que trabajase cerca',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: '@p.lira.z',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reducir el IVA ayudaría a reducir el costo de la vida, pero ello tendría que ir de la mano con un aumento de los impuestos progresivos, especialmente al capital acumulado y no a los ingresos.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Desde ya y hacia el futuro hombres y mujeres trabajarán indistitamente. Sin embargo, el cuidado de los niños por sus padres es un tema que me preocupa. Por eso, creo que debiera existir una ley que permita a cualquier trabajador, realizar su trabajo desde',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los parlamentarios tengan un sueldo normal, no exorbitante, para que la gente esté ahí por vocación y no por interés monetario. Mirar caso de Suecia https://www.google.cl/amp/s/www.bbc.com/mundo/amp/noticias-internacional-47280693',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar los sueldos vitalicios para nuestros presidentes.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Optimizar el trabajo de la cámara de diputados sesionando remotamente y delegando el trabajo distrital de campo y de comisiones.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Flvivanco@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear un filtro que verifique la vocación real de la persona cuando postule a un cargo público. Es decir, asegurarse (o filtrar mejor) que aquellos que postulen a un cargo público lo hagan por una vocación al servicio y no por una búsqueda, en primer luga',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Actualizar nuestro código penal, penas más duras a las situaciones que verdaderamente nos aquejan, para los delitos de cuello y corbata no pueden pasar a ser un costo hundido delinquir.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'gargantua5799@gmail.com',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Creo que debería haber un sueldo base de 500 mil pesos a todas las personas que cumplen el rol de cuidador de un sujeto que requiera cuidado y monitoreo constante de su estado de salud. Tengo una prima madre de 2 niñas de las cuales la menor sufre glucoge',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Trabajar en que los recursos sean más que suficientes para el SENAME y que NO se aguante una VIOLACIÓN más a los derechos humanos de estos pequeños indefensos y vulnerables. Que sean CASTIGADOS severamente por la ley aquellos que se atrevan a maltratarlos',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Así mismo, no abandonen a nuestra población de adultos mayores, la cual va cada vez más en incremento. \nPiensen que merecen llegar al final de su vida de manera DIGNA, y no recibiendo, no tratando de sobrevivir con una pensión tan INDIGNA como la que lle',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Actualizar nuestro código penal, penas más duras a las situaciones que verdaderamente nos aquejan, para los delitos de cuello y corbata no pueden pasar a ser un costo hundido delinquir.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Estatizar la producción y distribución eléctrica, financiar la inversión estructural con dineros previsionales.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Estatizar la producción y distribución eléctrica, financiar la inversión estructural con dineros previsionales.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Todos los nuevos proyectos de infraestructura (puentes, caminos, carreteras, puertos, aeropuertos, túneles, etc) financiarlos un cuarto el estado, dos cuartos privados y un cuarto AFPs (en representación de nosotros para aumentar nuestra futura pensión)',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Ngiturrate ',
              type: 'Proyecto dirigido a empresas',
              body: 'Sistema de pago en supermercados por bandas. Todo aquel que tenga un ingreso menor a $400.000 pague la mitad del total de la boleta. De esta forma, si las marcas suben sus precios para aumentar utilidades, los ricos se ven afectados a mayor escala.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ripacn2@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Básicamente que los funcionarios públicos, en especial de alto mando (presidente, ministros, etc), solo puedan ocupar los servicios que ofrece estado, tipo: sistema de salud, educación (para sus hijos), pensiones, etc. Así podrán encontrar fallas y soluci',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Enfermedades de salud mental cubiertas por el plan Auge ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Analizar bien los huella de carbono e hídrica de diversos productos y generar un impuesto verde para poder recaudar más dinero para combatir la desigualdad y al mismo tiempo, desincentivar el consumo de productos poco amigables con el medio ambiente. Por ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Mejor calidad de profesores',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Alonc.w',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Disminuir la segregación a base de un impusto sectorizado. La idea es que favoresca a las empresas que opten por ponerse en sectores con menos recursos.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El salario de los cargos públicos dependerá de la asistencia y cumplimiento de sus labores (ej. Diputado que no va a una sesión tiene un descuento en su remuneración mensual, como en cualquier trabajo), en conjunto, con la reducción de viaticos, entre otr',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '1) Bajar dieta parlamentaria en un 50% (sigue siendo un sueldo de lujo igual)\n2) Que eliminen el sueldo vitalicio a los ex presidentes (En qué empresa que dejas de trabajar te siguen pagando de por vida un sueldo y millonario más encima) \n3) Redistribuc',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Aliagamv@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Respetar y fortalecer la familia,devolviendole la autoridad y responsabilidad a los padres',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Elaborar planes de reinserción social para disminuir el ciclo delictivo al salir de la carcel, enfocandose en el problema personal que llevo a esa persona a delinquir (entorno social, alcoholismo, adicción, problemas económicos, etc), apoyado de una evalu',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Jaime-bravo@live.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Resignación de presupuestos y mayor aporte de municipalidades más ricas a más pobres ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que a cada auto al momento de la revisión técnica se le asigné un número, proporcional a cuánto contamina y en base a eso hayan restricciones en días que sea necesario, el sistema actual se basa en el falso supuesto de que mientras más viejo el auto más c',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Poner en urgencia la corrección del artículo 8 de la ley 20780, donde establece que el costo por pago del impuesto a las emisiones de CO2 lo deben pagar todas las empresas eléctricas que efectùen retiros de energía del sistema, lo que implica que empresas',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'IVA diferenciado según tipo de bienes: \nCanasta familiar básica (iva 10 %)\nBienes de lujo, cigarrillos, alcohol y autos sobre un cierto valor (iva 30%)\nResto de los bienes (iva 20 %)',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Valentinakobus@gmail.com',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Someter a consulta ciudadana formal (plebiscito) la aprobación del TPP-11. Es una decisión que nos afectará a todos; tanto en el ámbito de salud, económico, agricultura como medioambiental. Nadie ha informado de manera transparente sobre las consecuencias',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reducir cantidad de apitutados políticos en municipalidades, gobernaciones, etc.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar el hecho de que los empleados públicos no puedan ser echados ni evaluados por desempeño',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'lfgarridom@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Castigos ejemplares para actos de colusión y de corrupción. Que sea mayor la penalización que lo incurrido en daños (por ejemplo 50% más).',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Aumentar los cupos en la carrera medicina y otras carreras de la Salud. Hay tantos estudiantes hiper inteligentes y talentosos (que incluso ponderando sobre 750 en la psu) no logran entrar a medicina en las mejores universidades.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Jt.loayza',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Asamblea constituyente y cambios estructurales ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'famascaro@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Establecer un monto máximo que pueden recibir los cargos de las empresas asociadas al estado y licitaciones estatales como CODELCO, metro, transantiago, entre otras.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Otorgar al Sernac de capacidad fiscalizadora  real,  que le  duela a quien trate de coludirse , falsear precios  o engañar de cualquier forma a los consumidores.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Educación es el punto de inflexión de un país. No debiera ser manipulada por el gobierno u otro poder económico de turno, no debe ser comercializada como es hoy día.  La educación es el gran poder de un país para salir de la pobreza, desigualdades, etc.  ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Mrgonzalez@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear más espacios abiertos de divulgación científica. Propongo que la ciencia y la tecnología se tomen el espacio público con diversas intervenciones que llamen a niños y adultos a informarse y aprender. Podemos generar tecnológicas interactivas que nos ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Comisión del ministerio de hacienda que busque identificar y sancionar CONSIDERABLEMENTE a los evasores de impuestos y responsables de coludiones y estafas millonarias.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'desprivatizar el agua',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propuesta para mejorar la eduación básica y media en Chile que persiste aúm hasta el actual año 2019:\n\nCrear un proyecto de ley que establezca una educación igualitaria en base a una base de ingresos financiada de 2 formas: 1) por el estado y sus recurs',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Fenatellez',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '1) Educar a las personas respecto al funcionamiento de las AFP (Top 10 sistema de pensión a NIVEL MUNDIAL)  2) Hacer que las AFP cobren comisiones más bajas, y de manera progresiva (dado cierto rango de salario cobrar x monto y luego ir subiendo)  3) Fort',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bajar el IVA, que actualmente es de un 19% a un 4% para los productos de primera necesidad tales como: agua, artículos de aseo personal, pan, leche, etc.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Prohibir y regular ciertos proyectos inmobiliarios tales como guetos verticales y “nanodepartamentos”, establecer cantidades de m2 mínimos, y en caso de que se trate de departamentos pequeños establecer medidas compensatorias que mejoren la calidad de vid',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Creación de una app oficial, segura y gratuita a la que se cree una cuenta asociada a el rut y una contraseña, mediante la cual se puedan realizar sondeos y plebiscitos de manera efectiva para aumentar tanto la participación ciudadana como la democracia d',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminación de los conservadores de bienes raíces. En el sistema actual, son designados por el presidente de la república y obtienen sueldos injustificablemente altos (hasta 700 millones mensuales) que salen del bolsillo de los chilenos. Debido a la forma',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Hacer una ley de donación con importantes beneficios tributarios para que las empresas puedan donar para la reconstrucción',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'j.catalanvillablanca@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Mejoras crédito CAE',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar de manera considerable el impuesto a las drogas legales, como el alcohol, el tabaco y los cigarros.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Seguro universal de salud, transformando a isapres a empresas de seguro complementario donde un porcentaje tenga que ir a sistema publico. Prestadores privados y públicos',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Cambio de modelo. Estado subsidiario. Redistribuir ganancias de bienes nacionales e impuestos, en un orden de prioridades según real necesidad del país. Limitar y excluir al privado de acciones que le corresponderían al estado: educación, salud, energía, ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'La anulación del TPP-11 ya que se aprovo durante el movimiento social y su alto costo a la calidad de vida de los chilenos y chilenas',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Josefa.vasquez@usach.cl',
              instagram: 'Josefaypunto',
              type: 'Proyecto ciudadano',
              body: 'Mejorar la salud mental calando en los determinantes sociales ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Por que ir en contra de la naturaleza? La desigualdad existe y seguirá existiendo. Si uno quiere imponerse ante la adversidad, no queda más  remedio que dar todo de uno mismo a por ello. Repito de UNO MISMO. No esperemos que nos premien por el solo hecho ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'soficlement',
              type: 'Proyecto ciudadano',
              body: 'buses con bicileteros y mejorar la conectividad de las ciclovías en Santiago. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'vmonttb@yahoo.es',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear leyes duras en cuanto a la seguridad. Si te asaltan que cumplan penas en la carcel, si es necesario construir mas carceles y que ellos mismos trabajen dentro de ella para alimentarse.\n',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'fran_4399@hotmail.com ',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Desde hace años que todos hemos escuchado el término educación de calidad, sin embargo, nunca hemos especificado a qué nos referimos con ello. Personalmente, creo que este término trasciende lo académico y, por tanto, la educación de calidad debería enfoc',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'fran_4399@hotmail.com ',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Sin duda, los vínculos sociales son esenciales para la vida de cada ciudadano, por lo que la calidad de vida cambiaría si cada uno de nosotros trabajara en la misma comuna que habita y si los estudiantes asistieran a un colegio de la misma comuna. Así, pa',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fondos para hacer de chile un país turistico',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'pablorovetto',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que se nos calcule y pagué a todos pensiones como si viviéramos hasta los 83 y 88 años (hombres y mujeres), los que viven más, que lo cubra un seguro de longevidad pagado por el estado.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Crear una tarifa mensual en el sistema de transporte publico que este unida al rut de cada persona, no como la actual tarjeta BIP. Con esto se podría dirigir de mejor manera una tarifa diferenciada según el nivel de ingreso por ejemplo. Si una persona tie',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Lucas.cortes@mail.udp.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Somos de los países con mayores impuestos de la ocde. Ya sabemos que el estado no administra bien los recursos, y Piñera anunció que va a crear un impuesto de 40% a las rentas superiores a 8 millones. O sea, cualquier persona con una mediana empresa tendr',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Libros sin IVA',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fijar los sueldos en unidades de fomento (UF), y así evitar la pérdida de poder adquisitivo de los trabajadores, ya que, se iría reajustando y se terminaría con la problemática año a año.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Asamblea constituyente, es clave!!',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los politicos tengan que demostrar que estan capacitados para ejercer su cargo (titulo de autoridad en su area), asi se evitan cargos por pituto.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'L@s estudiantes de Medicina, una vez terminada la carrera, deberían realizar una práctica obligatoria por una cierta cantidad de meses en hospitales públicos (similar al caso de los abogados) para que en el ámbito de la Salud de Chile, existan más profesi',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Sueldo mensual que puede ser equivalente a lo que ganan los militares o carabineros para cada deportista seleccionado nacional para que se financie la carrera y el país logre mas clasificaciones olímpicas ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Recorte de gastos innecesarios como asistentes políticos y trabajadores gubernamentales innecesarios, y igualar la proporción de impuestos a empresas grandes con pymes',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar la reforma a afps realizada por Lagos. Esto significa que afiliados dejen de asumir las perdidas de las afps. No tiene sentido que nuestra prevision se vea afectada por culpa de un mal negocio.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'grcastro@uc.cl',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las empresas les paguen, al mes de Octubre los bonos por ventas a los trabajadores',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Hagamos que los sueldos de cargos públicos no sean fijos, sino que se limiten a mantener la vida de los funcionarios. En otras palabras, que en vez de pagar un sueldo fijo todos los meses, sean los mismos trabajadores que realicen un balance de cuentas de',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Jocelyn.kdh@gmail.com ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Cambiar a los administradores de los centros de salud, en todos sus niveles, los médicos deben salvar vidas, atender a las personas, no administrar los escasos recursos de la salud pública.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jocelyn.kdh@gmail.com ',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Evaluar la calidad del apoyo tecnológico que tienen los centros de salud, desde su infraestructura tecnológica, hasta las diversas plataformas donde deben ingresar la información de los usuarios, generando una gran pérdida de tiempo e ineficiencia en la i',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'flodonoso4',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Fijación de precios para consultas médicas, operaciones, intervenciones médicas y dentales.\nHoy en día se lucra mucho con esto, siendo uno de los mayores gastos dentro de una familia chilena, donde la salud debe ser un derecho de todos y al que muchos no',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'jocelyn.kdh@gmail.com ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Con la eficiencia que tiene Metro en el uso de los recursos, la experiencia en en transporte público y la cantidad de dinero que se inyecta anualmente a las empresas del TranSantiago, no es posible que este en manos del sector privado. El transporte públi',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'mrafols@uc.cl',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: '[Ahorro Solidario Intrageneracional] Que el sistema solidario de pensiones sea por un ahorro entre los miembros de una generación y no (solo) un ahorro individual, de tal manera que sin terminar con las AFPs (que es casi imposible) se logre una buena dist',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El PIE (proyecto de inclusión escolar) debería ser implementado en todos los colegios sin excepción asegurándose de adaptar las infraestructuras de todos los colegios y contar con profesionales que potencien el desarrollo de esos niños, como funciona en o',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bajar el impuesto a la comida ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Establecer una carta de deberes civiles para la ciudadanía para que ellos tengan la responsabilidad de velar y mantener tanto los bienes públicos como privados durante las marchas y entregar a las autoridades correspondientes a las personas que causen des',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar las restricciones anuales de atenciones de profesionales de  rehabilitación en el sistema FONASA para las personas con situación de discapacidad. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que los doctores tengan la obligación de trabajar en el servicio público (hospitales, APS)  al menos un 20% de su jornada.  ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'josecarvalloi',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reforzar los centros de Atención Primaria en Salud con mayor cantidad y variedad de profesionales de la salud. Fomentando actividades multidisciplinarias de prevención y diagnóstico oportuno de distintas condiciones de salud que puedan afectar a la poblac',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Que la clase politica DEBA ser ejemplo en el cumplimiento de la ley. Así, que si un político incumple con la ley tenga mayores consecuencias que lo normal (p.e suspencion mensual de sueldo; maximo de 3 faltas, si no, destitucion; entre otras opciones) tal',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'drvalle@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que las dietas parlamentarias sean proporcionales al Sueldo Mínimo y que a los diputados y senadores se les pague de acuerdo a su asistencia',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'drvalle@gmail.com',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Que las empresas cambien sus casas matrices a las regiones donde tienen su operación. Que paguen sus impuestos y patentes en las regiones.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Ya hemos hecho un gran trabajo etiquetando todos los alimentos altos en calorías, grasas y azúcares que sin duda perjudican nuestra salud. Dentro de la propuesta de un IVA diferenciado, podríamos recolectar más IVA en los productos que son nocivos para la',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'El impuesto específico existente a la bencina se aplicó para restaurar carreteras destruidas el año 1985, y aún sigue vigente. Dado que el impuesto sirve para recaudar fondos, la propuesta es eliminarlo para  aquellos que lo usan de manera particular (púb',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Drvalle@gmail.com',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Transformar nuestro Sistema de Salud Curativo a uno Preventivo. Debiésemos enfocarnos en evitar las enfermedades desde un punto de vista holistico en vez de enfocarnos en curar las enfermedades. Y para aquellas enfermedades catastróficas, cubrirlas en su ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'ptmedina@uc.cl',
              instagram: 'Pablomedina980',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que al momento de comprar cualquier cosa en la boleta aparezca el monto exacto de la parte del precio que corresponde al IVA u otro impuesto. Ejemplo de esto es EEUU. Así la gente sabría la cantidad de dinero que realmente paga en impuestos y estaría más ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Eliminar el impuesto específico ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Gaboxix@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Bueno hola parto con saludar, ya que encuentro bacan que estén dando estas instancias a la gente para poder expresar su opinión de la manera que estimen conveniente. Me encantaría saber que eso no se va a quedar en nada como la mayoría de las cosas que so',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aumentar el sueldo de los profesores. ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Stephitrautmann',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Para mejorar la educación, la carrera de pedagogía debería estar al mismo nivel que la carrera de medicina en términos de exigencia para el ingreso a estudiarla, y los sueldos deberían estar a la misma altura también, para que sea atractiva para los más c',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Aborto libre y seguro ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Mayor acceso a la cultura para todos los niveles socioeconómicos',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Se necesita invertir en el servicio de inteligencia.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'En E.E.U.U. existe el “earned income tax credit” donde a las personas más vulnerables se les devuelve parte del pago de impuestos, sujeto a que tengan que trabajar (alinea incentivos). Es una excelente medida para fomentar que la gente se emplee, que adem',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'elisarriagada97@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Se debiera hacer una “canasta básica de alimentos” que contenga todos los alimentos básicos y necesarios para una dieta saludable (siguiendo las recomendaciones del MINSAL): legumbres, carnes bajas en grasa, pescado, arroz, cereales, lácteos, papas, verdu',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'No se debería cobrar IVA a los productos de primera necesidad. Esto incluye medicamentos, pañales, confort, productos de higiene femenina...\nY en particular, cuestionarse la magnitud del impuesto específico a los combustibles (cercano al 40%).',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'elisarriagada97@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Continuando con mi propuesta anterior, se debería hacer una “canasta básica de medicamentos y productos farmacéuticos básicos”, que incluyan los medicamentos más utilizados y los dirigidos a las enfermedades más prevalentes de la población chilena. Estos ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'Mabelperez31@gmail.com',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'En salud cambiar al ministro, sanciones más drásticas a la colisión, aumentar el recurso destinado a este item... Mejorando la atención... Quitando recursos a la salud privada',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'Karinmas',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Que la educacion no sea un negocio, debe ser entregada por el Estado y que funcione, deberian cobrar impuestos (proporcionales a los ingresos de cada uno) solo dirigidos a la educacion. Los profesores deberian ganar mas sueldo, deberian tener mas benefici',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'En relacion a la propuesta que dice fijar precios maximos a horas de medicos, eso dificilmente es realizable. Sin embargo, actualmente muy pocos medicos estan atienden pacientes fonasa en sus consultas. La propuesta sería fijar por ley que todo medico deb',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'La gran mayoría de los problemas de la salid pública en Chile, se deben al mal manejo de los recursos entregados. Por lo tanto, debiera existir un cuerpo independiente de los centros y hospitales que se encargue de la administración (según las necesidades',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Exigir en cada carrera que sus alumnos participen en algún proyecto social. Desde una fundación, hasta incluso una práctica social. Así se logra concientizar a sus alumnos en poner su profesión al servicio de Chile.  ',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Ya que es dificil implementar cambios bruscos al sistema de AFPs, se podría implementar YA! que todos los pensionados reciban al menos el sueldo mínimo usando sus fondos, más adelante cuando se acaben el gobierno automáticamente los proveerá con la pensió',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto ciudadano',
              body: 'Proyecto a clases sociales que no tienen acceso a cultura y educación de calidad a través de workshops para enseñarles de educación civil y las políticas públicas a las que esta asociado nuestro país y cómo funcionan. Esto a través de la colaboración de d',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'nan',
              instagram: 'arichuaqui',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Volver al voto obligatorio y mantener la inscripción automática. Estos últimos días se ha hablado mucho sobre lo corrompida que esta toda la clase política, pero se nos olvida que la participación electoral fue menor que 50% para las elecciones presidenci',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Reducir el número de congresistas a 120 diputados y 40 senadores, manteniendo sistema proporcional y distritaje (más de 2 congresistas por distrito/ circunscripción) evitando volver al sistema electoral binominal.',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Proyecto dirigido a empresas',
              body: 'Qué pasa con :\n- Grandes Grupos económicos chilenos que han obtenido sus increíbles ganancias y no las invierten en Chile, sino en el extranjero. Ejemplos hay muchos: Paulman, Grupo Falabella. BCI, etc. \n¿Que impuestos pagan pagan por sacar el dinero de',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: false,
              email: 'mjdiestre@uc.cl ',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: ' Para bajar los precios del metro para los primeros quintiles (personas con menor ingreso), podrían eliminar la universalidad de la TNE y que no cubra a los estudiantes de los quintil más altos, porque ellos pueden pagar el precio normal del transporte. Q',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Propongo enseñar educación socioemocional a las chilenas y chilenos desde la primera niñez y a lo largo de toda la educación prescolar, escolar y superior. Que esto se incluya en las leyes que rigen  la educación es vital, pues se nos enseñan muchos conte',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      {
          privacy: true,
              email: 'nan',
              instagram: 'nan',
              type: 'Reforma/cambio a un Proyecto de Ley',
              body: 'Becas 100% Universidad Del Pacifico',
              approved: false,
              rating: 0,
              createdAt: new Date(),
              updatedAt: new Date(),
      },
      
      ];
      
    /*

      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkInsert('People', [{
        name: 'John Doe',
        isBetaMember: false
      }], {});
    */
   return queryInterface.bulkInsert('posts', postData);

  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
   return queryInterface.bulkDelete('posts', null, {});

  }
};
